version: '2'
networks:
    default:
        external:
            name: eclair_testnet

services:

    bitcoind:
        image: fleclerc2/bitcoind 
        container_name: bitcoindtest
        networks:
            default:
                ipv4_address: 172.18.0.2
        environment:
            - BTC_RUN_ARGS=-reindex
        
        volumes:
            - ../data:/bitcoin

        ports:
          - 8332:8332
          - 18332:18332
          - 8333:8333
          - 29000:29000
